{% set name = "openglider" %}
{% set version = "0.8.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/booya-at/OpenGlider/archive/{{ version }}.tar.gz
  sha256: 13a85ec37c0626c59d7ecaf730bdff919ba064bc5143c2139f807eefad6e5dbc

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  build:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - svgwrite
    - ezdxf
    - lxml
    - parabem
    - meshpy
    - pyexcel-ezodf
    - matplotlib-base
    - pyexcel-ods3

test:
  imports:
    - openglider

about:
  home: https://github.com/booya-at/OpenGlider
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: paraglider design
  dev_url: https://github.com/booya-at/OpenGlider

extra:
  recipe-maintainers:
    - looooo
