{% set name = "openglider" %}
{% set version = "0.05" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/booya-at/OpenGlider/archive/{{ version }}.tar.gz
  sha256: fb4b6137ab305d54dd92debf6b169a46fa2cc6a04621e279481b15b5aca260ff

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  build:
    - pip
    - python
  run:
    - python
    - numpy
    - svgwrite
    - ezdxf
    - lxml
    - parabem
    - meshpy
    - pyexcel-ezodf
    - matplotlib-base

test:
  imports:
    - openglider

about:
  home: https://github.com/booya-at/OpenGlider
  license: GPL-3
  license_family: GPL
  license_file: LICENSE
  summary: paraglider design
  dev_url: https://github.com/booya-at/OpenGlider

extra:
  recipe-maintainers:
    - looooo
