{% set name = "openglider" %}
{% set version = "0.0.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/booya-at/OpenGlider/archive/{{ version }}.tar.gz
  sha256: 066ed914c36985432a87c752e4931caa690856f13dad18f69207dcdc63b53b8d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  build:
    - pip
    - python
  run:
    - python
    - numpy
    - svgwrite
    - ezdxf
    - lxml
    - parabem
    - meshpy
    - pyexcel-ezodf
    - matplotlib-base

test:
  imports:
    - openglider

about:
  home: https://github.com/booya-at/OpenGlider
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: paraglider design
  dev_url: https://github.com/booya-at/OpenGlider

extra:
  recipe-maintainers:
    - looooo
