{% set name = "openglider" %}
{% set version = "0.0.6_cpp7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/booya-at/OpenGlider
  git_tag: cpp

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<37]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
  host:
    - pip
    - python
    - pybind11
    - ninja
  run:
    - python
    - numpy
    - svgwrite
    - ezdxf
    - lxml
    - parabem
    - meshpy
    - pyexcel-ezodf
    - pyexcel-ods3
    - matplotlib-base

test:
  imports:
    - openglider

about:
  home: https://github.com/booya-at/OpenGlider
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: paraglider design
  dev_url: https://github.com/booya-at/OpenGlider

extra:
  recipe-maintainers:
    - looooo
